#!/bin/bash
dir = "$HOME/.config/$XDG_CURRENT_DESKTOP"
read -r RICE < "$dir/.rice"

TIPS="$dir/rices/$RICE/widgets/System-Menu/scripts/tips/tips-lock"

STATUS=$(cat "$TIPS")

toggle() {
    if [[ $STATUS == "on" ]]; then
        echo "off" > "$TIPS"
        eww open --toggle tips
    else
        echo "on" > "$TIPS"
        eww open --toggle tips
    fi
}

icon() {
    if [[ $STATUS == "on" ]]; then
        echo ""
    else
        echo ""
    fi
}

status() {
    if [[ $STATUS == "on" ]]; then
        echo "Tips on"
    else
        echo "Tips off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
