[settings]
pseudo-transparency = true

[bar/top]
wm-name = polybar_top
monitor = ${system.sys_monitor}
width = 100%
height = 27
override-redirect = false
wm-restack = ${env:$XDG_CURRENT_DESKTOP:}


background = #11404040
foreground = #ccffffff

line-color = ${bar/bottom.background}
line-size = 3

spacing = 0
padding-right = 1
module-margin = 1


font-0 = "JetBrainsMono Nerd Font:size=8;3"
font-1 = "JetBrainsMono Nerd Font:size=50;20"
font-2 = "Font Awesome 6 Free:size=10;1"
font-3 = "JetBrainsMono Nerd Font:size=15;5"


modules-left =  powermenu mpd-title spotify
#modules-left =  powermenu music
modules-center = xwindow
modules-right =tray xkeyboard backlight volume wireless-network battery date ai-chat

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[bar/bottom]
wm-name = polybar_bottom
monitor = ${env:$XDG_CURRENT_DESKTOP:}
bottom = true
width = 100%
height = 24
override-redirect = false
wm-restack = ${env:$XDG_CURRENT_DESKTOP:}

background = ${bar/top.background}
foreground = ${bar/top.foreground}

line-color = ${bar/top.background}
line-size = 2

spacing = 1
padding-right = 1
module-margin-left = 0
module-margin-right = 2

font-0 = "JetBrainsMono Nerd Font:style=Regular:pixelsize=10;3"
font-1 = "Font Awesome 6 Free Regular:style=Regular:size=10;2"
font-2 = "JetBrainsMono Nerd Font:style=Regular:pixelsize=8;2"

modules-left = bspwm 
modules-center = mpd-progress
modules-right = cpu RAM disks

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; vim:ft=dosini
