#!/usr/bin/env bash

# Directory where to store temporary data
TMP_DIR="/tmp/rmpc"

# Ensure the directory is created
mkdir -p "$TMP_DIR"

# Where to temporarily store the album art received from rmpc
ALBUM_ART_PATH="$HOME/.config/eww/music-player/assets/cover.jpg"

# Path to fallback album art if no album art is found by rmpc/mpd
# Change this to your needs
DEFAULT_ALBUM_ART_PATH="$TMP_DIR/default_album_art.jpg"

# Save album art of the currently playing song to a file
if ! rmpc albumart --output "$ALBUM_ART_PATH"; then
  # Use default album art if rmpc returns non-zero exit code
  ALBUM_ART_PATH="${DEFAULT_ALBUM_ART_PATH}"
fi

# Send the notification
if [[ -n "$(command -v dunst)" ]]; then
  dunstify -r 1 -i "${ALBUM_ART_PATH}" "${TITLE^^}" "$ARTIST - $ALBUM"
else
  notify-send -i "${ALBUM_ART_PATH}" "${TITLE^^}" "$ARTIST - $ALBUM"
fi

LRCLIB_INSTANCE="https://lrclib.net"

if [ "$HAS_LRC" = "false" ]; then
  mkdir -p "$(dirname "$LRC_FILE")"

  if [ -z "$TITLE" ] || [ -z "$ARTIST" ]; then
    rmpc remote --pid "$PID" status "Skipping lyrics: incomplete metadata" --level warn
    exit 0
  fi

  RESPONSE="$(curl -X GET -sG --fail \
    -H "Lrclib-Client: rmpc-$VERSION" \
    --data-urlencode "artist_name=$ARTIST" \
    --data-urlencode "track_name=$TITLE" \
    --data-urlencode "album_name=$ALBUM" \
    "$LRCLIB_INSTANCE/api/get")" || {
      rmpc remote --pid "$PID" status "Network error fetching lyrics" --level error
      exit 1
    }

  LYRICS="$(echo "$RESPONSE" | jq -r '.syncedLyrics')"

  if [ -z "$LYRICS" ]; then
    rmpc remote --pid "$PID" status "Failed to download lyrics for $ARTIST - $TITLE" --level error
    exit 0
  fi

  if [ "$LYRICS" = "null" ]; then
    rmpc remote --pid "$PID" status "Lyrics for $ARTIST - $TITLE not found" --level warn
    exit 0
  fi

  echo "[ar:$ARTIST]" >"$LRC_FILE"
  {
    echo "[al:$ALBUM]"
    echo "[ti:$TITLE]"
  } >>"$LRC_FILE"
  echo "$LYRICS" | sed -E '/^\[(ar|al|ti):/d' >>"$LRC_FILE"

  rmpc remote --pid "$PID" indexlrc --path "$LRC_FILE"
  rmpc remote --pid "$PID" status "Downloaded lyrics for $ARTIST - $TITLE" --level info
fi
