cursor            #82d3e0
cursor_text_color #00363d

foreground            #dee3e5
background            #090f10
selection_foreground  #1c3438
selection_background  #b1cbd0
url_color             #b1cbd0

#: black 000000 767676
color0  #0e1415
color8  #303637
#: red cc0403 f2201f
color1  #f00190
color9  #fe8cd0
#: green 19cb00 23fd00
color2  #b1cbd0
color10 #cde7ec
#: yellow cecb00 fffd00
color3  #bac6ea
color11 #dae2ff
#: blue 0d73cc 1a8fff
color4  #004f58
color12 #82d3e0
#: magenta cb1ed1 fd28ff
color5  #334b4f
color13 #b1cbd0
#: cyan 0dcdcd 14ffff
color6  #3b4664
color14 #bac6ea
#: white dddddd ffffff
color7  #bfc8ca
color15 #dee3e5

mark1_foreground #001f24
mark1_background #9eeffd
mark2_foreground #051f23
mark2_background #cde7ec
mark3_foreground #0e1b37
mark3_background #dae2ff

active_tab_foreground #00363d
active_tab_background #82d3e0
inactive_tab_foreground #9eeffd
inactive_tab_background #004f58

active_border_color #82d3e0
inactive_border_color #00363d
bell_border_color #ff5a00
