include ~/.cache/wal/colors-kitty.conf

cursor_text_color     #442b00
url_color             #ddc3a1
selection_foreground  #3d2e16
selection_background  #ddc3a1

mark1_foreground #291800
mark1_background #ffddb1
mark2_foreground #271904
mark2_background #fadebc
mark3_foreground #0f2004
mark3_background #d3eabd
