cursor            #cfff96
cursor_text_color #000000

foreground            #ffffff
background            #000000
selection_foreground  #000000
selection_background  #d8f9d2
url_color             #d8f9d2

#: black 000000 767676
color0  #10150a
color8  #43493b
#: red cc0403 f2201f
color1  #ee5700
color9  #ffb388
#: green 19cb00 23fd00
color2  #b0cfaa
color10 #cbebc5
#: yellow cecb00 fffd00
color3  #99d3b0
color11 #b4f0cb
#: blue 0d73cc 1a8fff
color4  #081400
color12 #cfff96
#: magenta cb1ed1 fd28ff
color5  #001603
color13 #d8f9d2
#: cyan 0dcdcd 14ffff
color6  #00150a
color14 #c1fed8
#: white dddddd ffffff
color7  #ffffff
color15 #ffffff

mark1_foreground #000000
mark1_background #9cfb00
mark2_foreground #000000
mark2_background #cbebc5
mark3_foreground #000000
mark3_background #b4f0cb

active_tab_foreground #000000
active_tab_background #cfff96
inactive_tab_foreground #000000
inactive_tab_background #86d800

active_border_color #cfff96
inactive_border_color #000000
bell_border_color #ff5a00
