#!/usr/bin/env bash

source ~/.ssh/var

USER="$username"
TOKEN="$token"

notifications=$(
  curl -s \
    -H "Authorization: Bearer $TOKEN" \
    -H "Accept: application/vnd.github+json" \
    https://api.github.com/notifications \
  | jq '[ .[] | select(.unread == true) ] | length'
)

echo "$notifications"
