#!/usr/bin/env bash

# Toggle bsp-layout layouts

read -r RICE < "$HOME/.config/$XDG_CURRENT_DESKTOP/.rice"

path="$HOME/.config/$XDG_CURRENT_DESKTOP/rices/$RICE/scripts/current-layout"

# Default state
if [[ ! -f "$path" ]]; then
    echo "[~]" > "$path"
fi

read -r CURRENT < "$path"

case "$CURRENT" in
    "[~]")
        bsp-layout set tiled
        echo "[=]" > "$path"
        ;;

    "[=]")
        bsp-layout set monocle
        echo "[M]" > "$path"
        ;;

    "[M]")
        bsp-layout set grid
        echo "[|]" > "$path"
        ;;

    "[|]")
        bsp-layout set wide
        echo "[*]" > "$path"
        ;;

    "[*]")
        bsp-layout set even
        echo "[~]" > "$path"
        ;;

    *)
        # fallback jika isi file rusak/tidak dikenal
        bsp-layout set tiled
        echo "[=]" > "$path"
        ;;
esac
