#!/bin/bash
dir="$HOME/.config/$XDG_CURRENT_DESKTOP"
read -r RICE < "$dir/.rice"

if [[ $1 == "--toggle" ]]; then
        if pgrep tint2; then
                pkill tint2
                echo "" > "$dir/rices/scripts/tray-status"
                exit 1
        else
                eww open --toggle background-closer && tint2 &
                echo "" > "$dir/rices/scripts/tray-status"
        fi
        exit
fi

if [[ $1 == "--kill" ]]; then
        pkill tint2
        echo "" > "$dir/rices/scripts/tray-status"
        exit 1
fi
