[ChatAi]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/ChatAi.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[ClaudeAi]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/ClaudeAi.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[GeminiAi]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/GeminiAi.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[Spotify]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/Spotify.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[St]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/St.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[TerminalDefault]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/TerminalDefault.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[TerminalPinned]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/TerminalPinned.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=false
SkipPager=false
SkipTaskbar=false
Sticky=false

[Terminalnvim]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/Terminalnvim.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[_GLOBAL_DEFAULTS]
BalloonTimeout=4000
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=false
SkipPager=false
SkipTaskbar=false
Sticky=false

[floating_rmpc]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/floating_rmpc.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false

[vesktop]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/vesktop.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=false
SkipPager=false
SkipTaskbar=false
Sticky=false

[youtube]
BalloonTimeout=4000
CustomIcon=/home/tquilla/.config/com.kdocker/icons/youtube.png
IconifyDocking=false
IconifyFocusLost=false
IconifyMinimized=false
IconifyObscured=false
LockToDesktop=true
Quiet=true
SkipPager=false
SkipTaskbar=false
Sticky=false
