[config]

[templates.gtk3]
input_path = "templates/gtk3-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"
# post_hook = ""

[templates.gtk4]
input_path = "templates/gtk4-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.helix]
input_path = "templates/helix.toml"
output_path = "~/.config/helix/themes/racooon.toml"

[templates.bspwm]
input_path = "templates/bspwm"
output_path = "~/.config/bspwm/bin/colors"
post_hook = "sh ~/.config/bspwm/bin/colors"

[templates.btop]
input_path = "templates/btop.theme"
output_path = "~/.config/btop/themes/racooon.theme"

[templates.yazi]
input_path = "templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.rofi]
input_path = "templates/rofi-colors.rasi"
output_path = "~/.config/rofi/themes/shared.rasi"

[templates.xresources]
input_path = "templates/xresources"
output_path = "~/.Xresources"
post_hook = "xrdb -merge ~/.Xresources && killall -USR1 st"

[templates.wallpaper]
input_path = "templates/setwall"
output_path = "~/.config/bspwm/bin/wallpaper"
post_hook = "wallpaper"

[templates.environment]
input_path = "templates/env"
output_path = "~/.dynamic"

# [templates.vivaldi]
# input_path = "templates/vivaldi.css"
# output_path = "~/.config/vivaldi/CustomCSS/colors.css"
