[config]

[templates.gtk3]
input_path = "templates/gtk3-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "templates/gtk4-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.helix]
input_path = "templates/helix.toml"
output_path = "~/.config/helix/themes/helix.toml"

# [templates.vivaldi]
# input_path = "templates/vivaldi.css"
# output_path = "~/.config/vivaldi/CustomCSS/colors.css"
