[config]

[templates.gtk]
input_path = "templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.vivaldi]
input_path = "templates/vivaldi.css"
output_path = "~/.config/vivaldi/CustomCSS/colors.css"
