{ pkgs, config, ... }:
{


  stylix = {
    enable = true;

    # Whether to enable targets by default.
    # When this is false, all targets are disabled unless explicitly enabled.
    autoEnable = true;

    # Whether to enable theming for packages via overlays.
    # Default : config.stylix.autoEnable
    overlays.enable = false; # boolean

    ## A scheme following the base16 standard.
    ## Default : Automatically selected from the background image.
    ## The default will throw if config.stylix.image is null.
    ## This can be a path to a file, a string of YAML, or an attribute set.
    # base16Scheme = null;

    # An override that will be applied to stylix.base16Scheme when generating config.lib.stylix.colors.
    # Takes anything that a scheme generated by base16nix can take as argument to override.
    override = {
      base00 = "#190f0f"; # Main bg : terminal bg, editor bg, apps main bg
      base01 = "#e71520"; # Status bar background, Line highlight, Panel
      # base02 = "#995a41"; # Selection : Selected text, Visual Selection, Active window highlight
      # base03 = "#c79270"; # Comments : Komentar kode, line number, inactive text
      # base04 = "#feab99"; # Secondary fg : UI border, Placeholder,
      # base05 = "#c3e9f6"; # Main fg
      # base06 = "#ecf0f1"; # Bold fg
      # base07 = "#fef2be"; # light bg/fg
      # base08 = "#e46d54"; # Semantic hightlight, syntax (Error msg, deleted diff)
      # base09 = "#f75c4f"; # NUmber litrals, COnstants
      # base0A = "#c77f5f"; # Class, Type, Attribute
      # base0B = "#d77659"; # Strings, Succes, added diff
      # base0C = "#c77e65"; # Special symbols, Escape chars
      # base0D = "#cc7c5e"; # Function name, Method, Links
      # base0E = "#fa5a46"; # Keywords, Storage modifiers, tag names
      # base0F = "#ba8563"; # Deprecated, Special operator, Rare Syntax.
    };

    # Whether to check that the Stylix release matches the releases of NixOS, Home Manager, and nix-darwin.
    # If this option is enabled and a mismatch is detected,
    # a warning will be printed when the user configuration is being built.
    enableReleaseChecks = true;

    polarity = "dark"; # "dark","light"

    imageScalingMode = "fill"; # stretch, fill, fit, center, tile
    image = pkgs.fetchurl {
      url = "https://raw.githubusercontent.com/msalmanrafadhlih/Dotfiles/refs/heads/bspwm/home/Assets/Wallpaper/wallpaper8.jpeg";
      hash = "sha256-VZp1wy2N0GApt48ILRY+pIAhAjCt02GmqmxHRTWAEoA=";
    };
    # image = pkgs.fetchurl {
    #   url = "https://raw.githubusercontent.com/msalmanrafadhlih/Dotfiles/refs/heads/bspwm/home/Assets/Wallpaper/wallpaper11.jpg";
    #   hash = "sha256-SToNXY0LihjfCsfqgkzXfAT8B19t/HY48TrqfwgoiJc=";
    # };

    ########
    # Opacity Default = 1.0
    opacity = {
      # The opacity of the windows of applications,
      applications = 0.5;
      # The opacity of the windows of bars/widgets,
      desktop = 0.5;
      # The opacity of the windows of notifications/popups,
      popups = 0.5;
      # The opacity of the windows of terminals,
      terminal = 0.4;
    };

    ## Attributes defining the systemwide cursor.
    ## Set either all or none of these attributes.
    cursor = {
      name = "Kafka";
      size = 24;
      package = pkgs.callPackage (pkgs.fetchFromGitHub {
        owner = "TQ-See";
        repo = "Cursors-memes";
        rev = "main";
        sha256 = "sha256-rvq2XKiv9fkLBE9LbPIBGu2ekYhypCQlYW42P9OgmVo=";
      }) { };
    };

    ##########
    ## Fonts Theming
    fonts = {
      sizes = {
        applications = 10;
        desktop = 10;
        popups = config.stylix.fonts.sizes.desktop;
        terminal = config.stylix.fonts.sizes.applications;
      };

      emoji = {
        name = "Noto Color Emoji";
        package = pkgs.noto-fonts-color-emoji;
      };

      monospace = {
        name = "JetBrainsMono Nerd Font"; # Font coding paling enak
        package = pkgs.nerd-fonts.jetbrains-mono;
      };

      sansSerif = {
        name = "Inter"; # UI aplikasi jadi terlihat modern
        package = pkgs.inter;
      };

      serif = {
        name = "Noto Serif";
        package = pkgs.noto-fonts;
      };
    };

    #########
    # Icons Theming
    icons = {
      enable = true;
      # Nama di sini harus sesuai dengan nama folder di dalam /share/icons/
      # ls $(nix-build -E "with import <nixpkgs> {}; vimix-icon-theme")/share/icons
      dark = "Vimix-ruby-dark";
      light = "Vimix-ruby";
      package = pkgs.vimix-icon-theme;
    };
  };
  # Target Applications
  imports = [
    ./gtk.nix
    ./disable.nix
  ];
}
