[Appearance]
custom_palette=true
icon_theme=Vimix-ruby-dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed="JetBrainsMono Nerd Font,10"
general="Inter,10"

[ColorScheme]
active_colors=#f9dcd9, #1e100f, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f9dcd9, #ffffff, #ffffff, #1e100f, #1e100f, #000000, #ffaea7, #000000, #ffece6, #ffecea, #1e100f, #000000, #1e100f, #ffffff, #ffece6
disabled_colors=#f9dcd9, #1e100f, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f9dcd9, #ffffff, #ffffff, #1e100f, #1e100f, #000000, #ffaea7, #000000, #ffece6, #ffecea, #1e100f, #000000, #1e100f, #ffffff, #ffece6
inactive_colors=#f9dcd9, #1e100f, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f9dcd9, #ffffff, #ffffff, #1e100f, #1e100f, #000000, #ffaea7, #000000, #ffece6, #ffecea, #1e100f, #000000, #1e100f, #ffffff, #ffece6

