#!/bin/sh

case "$1" in
    "icon")
        STATUS=$(cat /sys/class/power_supply/BAT0/status)
        PERCENTAGE=$(cat /sys/class/power_supply/BAT0/capacity)

        if [ "$STATUS" = "Charging" ]; then
            echo ""
        else
            if [ "$PERCENTAGE" -gt 90 ]; then echo ""
            elif [ "$PERCENTAGE" -gt 65 ]; then echo ""
            elif [ "$PERCENTAGE" -gt 40 ]; then echo ""
            elif [ "$PERCENTAGE" -gt 10 ]; then echo ""
            else echo ""
            fi
        fi
        ;;
    "percent")
        cat /sys/class/power_supply/BAT0/capacity
        ;;
esac
