#!/usr/bin/env bash
MODE=$(powerprofilesctl get)

toggle() {
    if [[ $MODE == 'balanced' ]]; then
        powerprofilesctl set performance
    else
        powerprofilesctl set balanced
    fi
}

icon() {
    if [[ $MODE == 'balanced' ]]; then
        echo "󰔢"
    else
        echo "󰔡"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--mode" ]]; then
    echo $MODE
elif [[ $1 == "--icon" ]]; then
    icon
fi
