#!/usr/bin/env bash
STATUS=$(pamixer --get-mute)

toggle() {
    if [ "$STATUS" == "false" ]; then
        pamixer --mute
        dunstify --icon=volume-level-muted --urgency=normal "Volume" "Volume has been muted!"
    else
        pamixer --unmute
        dunstify --icon=volume-level-high --urgency=normal "Volume" "Volume has been unmuted!"
    fi
}

icon() {
    if [ "$STATUS" == "false" ]; then
        echo "󰕾"
    else
        echo "󰖁"
    fi
}

status() {
    if [ "$STATUS" == "false" ]; then
        echo "On"
    else
        echo "Off"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
fi
