#!/bin/bash

dir="$HOME/.config/$XDG_CURRENT_DESKTOP"
read -r RICE < "$dir/.rice"

EWW="$dir/rices/$RICE/widgets"
read -r STATE < "$EWW/Player/status/ly-status"

if [[ $STATE == "On" ]]; then
    eww -c "$EWW" daemon && eww -c "$EWW" close visualizer lyrics 
    pkill glava 
    echo "Off" > "$EWW/Player/status/ly-status"
else
    eww -c "$EWW" daemon && eww -c "$EWW" open lyrics
    eww -c "$EWW" daemon && eww -c "$EWW" close visualizer &
    pkill visualizer
    echo "On" > "$EWW/Player/status/ly-status"
fi
exit
