#!/bin/sh

# Mengambil daftar workspace yang ada (occupied), kosong (empty), dan yang aktif (focused)
bspc query -D --names | while read -r name; do
    occupied_desktops=$(bspc query -D -d .occupied --names)
    focused_desktop=$(bspc query -D -d .focused --names)

    class="empty"
    if [ "$name" = "$focused_desktop" ]; then
        class="active"
    elif echo "$occupied_desktops" | grep -q "^$name$"; then
        class="occupied"
    fi
    
    # Hanya tampilkan workspace 1-5
    case $name in
        [1-5])
            echo -n "(button :class '$class' :onclick 'bspc desktop -f $name' '$name') "
            ;;
    esac
done
echo
