#!/usr/bin/env bash

icon() {
    if [[ "$(pamixer --get-mute)" == "false" ]]; then
        vol=$(pamixer --get-volume)

        if [[ ${vol} -ge 80 ]]; then
            echo "󰕾"
        elif [[ ${vol} -ge 40 ]]; then
            echo "󰖀"
        elif [[ ${vol} -ge 10 ]]; then
            echo "󰕿"
        else
            echo "󰝟"
        fi
    else
        echo "󰝟"
    fi
}

getvol() {
    pamixer --get-volume
}

if [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--value" ]]; then
    getvol
fi
