#!/bin/sh

bspc monitor -d 1 2 3 4 5 6

# Set environment variables
export PATH="$HOME/.config/bspwm/bin:$HOME/.local/bin:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

run() {
    if ! pidof -q "$1"; then
        "$@" &
    fi
}

bspc config external_rules_command ~/.config/bspwm/bin/ExternalRules

# Border
bspc config left_padding 50
bspc config border_width 3
bspc config window_gap 5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Behavior
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

CornerLogic &
Colors &
~/.fehbg &
LaunchBar &
Dock &

pgrep -x clipmenud > /dev/null || clipmenud &
pgrep -x picom > /dev/null || picom &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
