#!/bin/sh
#
# monitor setup
bspc monitor -d [I] [II] [III] [IV] [V]

#bspc rule -a Alacritty desktop=^1
#bspc rule -a code-oss desktop=^3

# Set environment variables
export PATH="$HOME/.local/bin:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

run() {
    if ! pidof -q "$1"; then
        "$@" &
    fi
}

# Border
bspc config border_width 3
bspc config window_gap 5
bspc config focused_border_color "#c80e15"
bspc config normal_border_color "#3B4252"
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config pointer_motion_interval 7
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Behavior
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config removal_adjustment true

bspc config external_rules_command ~/.config/bspwm/src/ExternalRules

# picom
pkill picom
sleep 0.1
picom &

# Clipboard manager
clipmenud &

# Autostart background dengan slideshow 10 menit
~/.local/bin/bg-slideshow

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
chmod +x ~/.config/polybar/launch.sh
~/.config/polybar/launch.sh &

#eww
chmod +x ~/.config/eww/scripts/*
#eww daemon && eww open topbar

# dunst untuk widget notifikasi
pgrep -x dunst > /dev/null || dunst &

chmod +x ~/.local/bin/*
update-desktop-database ~/.local/share/applications/

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax)"
fi

pkill daktilo
daktilo --config ~/.config/daktilo/daktilo.toml --preset ducduggo -d pipewire
