[module/tray2]
type = internal/tray

format = <tray>
format-background = ${color.tray-bg}
tray-background = ${color.tray-bg}
# tray-foreground = ${color.fg}
tray-spacing = 10
tray-padding = 0
tray-size = 45%

[module/workspace2]
type = internal/bspwm
format = <label-state>

label-focused = "%{T5}%{T-}"
label-focused-padding = 1

label-occupied = "%{T5}%{T-}"
label-occupied-padding = 1

label-empty = "%{T5}%{T-}"
label-empty-padding = 1
