# spotify and mpd
# spotify and mpd
# spotify and mpd
# spotify and mpd

[module/spotify]
type                = custom/script
interval            = 2
exec                = playerctl-status &
exec-if             = pgrep -x spotify > /dev/null

click-left          = playerctl -p spotify play-pause
click-right         = playerctl -p spotify next
click-middle        = playerctl -p spotify previous
scroll-up           = playerctl -p spotify next
scroll-down         = playerctl -p spotify previous

format              = <label>
format-prefix       = "  "
format-prefix-foreground = #00ff00

label               = %output%
label-maxlen        = 50       
