# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MODULAR CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# source = ~/.config/hypr/colors.conf

submap = passthru
# Dummy bind to force Hyprland to register the submap in memory.
# Since we will never press this, all normal keystrokes fall through to Quickshell
bind = SUPER SHIFT CTRL ALT, F35, exec, true
submap = reset

# --------------

source = ~/.config/hypr/oldconfig/monitors.conf
source = ~/.config/hypr/oldconfig/env.conf
source = ~/.config/hypr/oldconfig/autostart.conf
source = ~/.config/hypr/oldconfig/variables.conf
source = ~/.config/hypr/oldconfig/settings.conf
source = ~/.config/hypr/oldconfig/rules.conf
source = ~/.config/hypr/oldconfig/keybindings.conf
