#!/bin/sh

bspc config focused_border_color "{{ colors.source_color.default.hex | to_color | set_lightness: 70 }}"
bspc config normal_border_color "#3B4252"
bspc config active_border_color "{{ base16.base0d.default.hex }}"
bspc config presel_feedback_color "{{ base16.base00.default.hex }}"
