"attribute" = "blue0"
"comment" = { fg = "{{ base16.base03.default.hex | to_color | lighten: 20.0 }}", modifiers = [
  "italic",
] }
"constant" = { fg = "orange0" }
"constant.builtin" = { fg = "orange0", modifiers = ["bold"] }
"constant.character.escape" = { fg = "orange0", modifiers = ["bold"] }
"constant.numeric" = "orange0"
"constructor" = { fg = "blue0", modifiers = ["bold"] }
"function" = { fg = "green0", modifiers = ["bold"] }
"function.builtin" = "green0"
"function.macro" = "green0"
"keyword" = { fg = "orange1" }
"label" = "blue0"
"module" = "blue0"
"namespace" = "pink2"
"operator" = "orange1"
"punctuation" = "orange1"
"special" = "pink2"
"string" = "{{ colors.primary.default.hex | to_color | set_lightness: 70 | set_saturation: 50.0 }}"
# "string.regexp" = "{{ colors.tertiary_container.default.hex }}"
# "string.special" = "{{ colors.primary_fixed.default.hex }}"
# "string.special.symbol" = "{{ colors.error.default.hex }}"
"tag" = "green0"
"type" = "blue0"
"type.builtin" = "orange0"
"variable" = "white0"
"variable.builtin" = "blue0"
"variable.other.member" = "blue0"
"variable.parameter" = "green1"

"diff.delta" = "violet0"
"diff.minus" = "pink2"
"diff.plus" = "green1"

"error" = "orange1"
"hint" = "white0"
"info" = "blue0"
"warning" = "green1"

# --- UI Elements ---

"ui.background" = { fg = "{{ colors.on_background.default.hex }}", bg = "none" }
"ui.linenr" = { fg = "{{ colors.on_surface_variant.default.hex }}" }
"ui.linenr.selected" = { fg = "{{ colors.primary_fixed.default.hex }}" }
"ui.statusline" = { fg = "{{ colors.on_primary_container.default.hex }}", bg = "none" }
"ui.statusline.inactive" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.statusline.normal" = { fg = "green0", bg = "none", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "orange1", bg = "none", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "blue0", bg = "none", modifiers = ["bold"] }
"ui.popup" = { fg = "{{ colors.on_surface.default.hex }}", bg = "none" }
"ui.window" = { fg = "{{ colors.on_surface_variant.default.hex }}" }
"ui.help" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.bufferline" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.bufferline.active" = { fg = "{{ colors.on_primary.default.hex }}", bg = "{{ colors.primary.default.hex }}" }
"ui.bufferline.background" = { bg = "none" }
"ui.text" = "{{ colors.on_background.default.hex }}"
"ui.text.focus" = { fg = "{{ colors.primary.default.hex }}", bg = "none", modifiers = [
  "bold",
] }
"ui.text.inactive" = { fg = "{{ colors.on_surface_variant.default.hex }}" }
"ui.text.directory" = { fg = "{{ colors.primary.default.hex }}" }
"ui.virtual" = "{{ colors.on_surface_variant.default.hex }}"
"ui.virtual.ruler" = { bg = "none" }
"ui.virtual.indent-guide" = "{{ colors.surface_container_low.default.hex }}"
"ui.virtual.inlay-hint" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.virtual.jump-label" = { fg = "{{ colors.primary_container.default.hex }}", modifiers = [
  "bold",
] }
"ui.selection" = { bg = "{{ base16.base02.default.hex }}" }
"ui.cursor" = { fg = "{{ colors.background.default.hex }}", bg = "{{ base16.base02.default.hex | to_color | set_lightness: 70.0 }}" }
"ui.cursor.primary" = { fg = "{{ colors.background.default.hex }}", bg = "{{ colors.primary_fixed.default.hex }}" }
"ui.cursor.match" = { fg = "{{ colors.primary.default.hex }}", bg = "{{ base16.base02.default.hex }}" , modifiers = [
  "bold",
] }
"ui.highlight" = { bg = "{{ colors.secondary_container.default.hex }}", modifiers = [
  "bold",
] }
"ui.menu" = { fg = "green0", bg = "none" }
"ui.menu.selected" = { fg = "orange1", modifiers = ["bold"] }

# --- Diagnostics ---

"diagnostic.error" = { fg = "{{ colors.error.default.hex }}" }
"diagnostic.warning" = { fg = "{{ colors.secondary.default.hex }}" }
"diagnostic.info" = { fg = "{{ colors.tertiary.default.hex }}" }
"diagnostic.hint" = { fg = "{{ colors.tertiary_container.default.hex }}" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }

"markup.strikethrough" = { modifiers = ["crossed_out"] }

[palette]
blue0 = "#65aba3"

dark_red0 = "#190f0f"
dark_red1 = "#331c1e"
dark_red2 = "#2c1617"
dark_red3 = "#442022"
dark_red4 = "#704144"

green0 = "#8ea84d"
green1 = "#6db269"

orange0 = "#ff7550"
orange1 = "#eb842b"

pink0 = "#622b30"
pink1 = "#d2505f"
pink2 = "#d95362"
pink3 = "#c79295"
pink4 = "#e97e8a"

violet0 = "#ce8b9f"

white0 = "#cebabf"
