"attribute" = "blue0"
"comment" = { fg = "pink1", modifiers = ["italic"] }
"constant" = { fg = "orange0" }
"constant.builtin" = { fg = "orange0", modifiers = ["bold"] }
"constant.character.escape" = { fg = "orange0", modifiers = ["bold"] }
"constant.numeric" = "orange0"
"constructor" = { fg = "blue0", modifiers = ["bold"] }
"function" = { fg = "green0", modifiers = ["bold"] }
"function.builtin" = "green0"
"function.macro" = "green0"
"keyword" = { fg = "orange1" }
"label" = "blue0"
"module" = "blue0"
"namespace" = "pink2"
"operator" = "orange1"
"punctuation" = "orange1"
"special" = "pink2"
"string" = "violet0"
"tag" = "green0"
"type" = "blue0"
"type.builtin" = "orange0"
"variable" = "white0"
"variable.builtin" = "blue0"
"variable.other.member" = "blue0"
"variable.parameter" = "green1"

"error" = "orange1"
"hint" = "white0"
"info" = "blue0"
"warning" = "green1"

# --- Diff ---

"diff.delta" = "violet0"
"diff.minus" = "pink2"
"diff.plus" = "green1"

# --- Markup ---

"markup.heading.1" = "{{ colors.error.default.hex }}"
"markup.heading.2" = "{{ colors.primary.default.hex }}"
"markup.heading.3" = "{{ colors.secondary.default.hex }}"
"markup.heading.4" = "{{ colors.tertiary.default.hex }}"
"markup.heading.5" = "{{ colors.primary_fixed.default.hex }}"
"markup.heading.6" = "{{ colors.on_primary_fixed_variant.default.hex }}"

"markup.list" = "{{ colors.secondary.default.hex }}"
"markup.list.unchecked" = "{{ colors.on_surface_variant.default.hex }}"
"markup.list.checked" = "{{ colors.primary_fixed.default.hex }}"

"markup.bold" = { fg = "{{ colors.primary.default.hex }}", modifiers = [
  "bold",
] }
"markup.italic" = { fg = "{{ colors.secondary.default.hex }}", modifiers = [
  "italic",
] }

"markup.link.url" = { fg = "{{ colors.primary.default.hex }}", modifiers = [
  "italic",
  "underlined",
] }
"markup.link.text" = "{{ colors.primary_fixed.default.hex }}"
"markup.link.label" = "{{ colors.tertiary.default.hex }}"
"markup.raw" = "{{ colors.on_tertiary_container.default.hex }}"
"markup.quote" = "{{ colors.tertiary_container.default.hex }}"

# --- UI Elements ---

"ui.background" = { fg = "{{ colors.on_background.default.hex }}", bg = "none" }

"ui.linenr" = { fg = "{{ colors.on_surface_variant.default.hex }}" }
"ui.linenr.selected" = { fg = "{{ colors.primary_fixed.default.hex }}" }

"ui.statusline" = { fg = "{{ colors.on_primary_container.default.hex }}", bg = "none" }
"ui.statusline.inactive" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.statusline.normal" = { fg = "{{ colors.background.default.hex }}", bg = "none", modifiers = [
  "bold",
] }
"ui.statusline.insert" = { fg = "{{ colors.background.default.hex }}", bg = "none", modifiers = [
  "bold",
] }
"ui.statusline.select" = { fg = "{{ colors.background.default.hex }}", bg = "none", modifiers = [
  "bold",
] }

"ui.popup" = { fg = "{{ colors.on_surface.default.hex }}", bg = "none" }
"ui.window" = { fg = "{{ colors.on_surface_variant.default.hex }}" }
"ui.help" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }

"ui.bufferline" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.bufferline.active" = { fg = "{{ colors.on_primary.default.hex }}", bg = "{{ colors.primary.default.hex }}" }
"ui.bufferline.background" = { bg = "none" }

"ui.text" = "{{ colors.on_background.default.hex }}"
"ui.text.focus" = { fg = "{{ colors.primary.default.hex }}", bg = "none", modifiers = [
  "bold",
] }
"ui.text.inactive" = { fg = "{{ colors.on_surface_variant.default.hex }}" }
"ui.text.directory" = { fg = "{{ colors.primary.default.hex }}" }

"ui.virtual" = "{{ colors.on_surface_variant.default.hex }}"
"ui.virtual.ruler" = { bg = "none" }
"ui.virtual.indent-guide" = "{{ colors.surface_container_low.default.hex }}"
"ui.virtual.inlay-hint" = { fg = "{{ colors.on_surface_variant.default.hex }}", bg = "none" }
"ui.virtual.jump-label" = { fg = "{{ colors.primary_container.default.hex }}", modifiers = [
  "bold",
] }

"ui.selection" = { bg = "{{ colors.outline_variant.default.hex }}" }

"ui.cursor" = { fg = "{{ colors.background.default.hex }}", bg = "{{ colors.on_primary_container.default.hex }}" }
"ui.cursor.primary" = { fg = "{{ colors.background.default.hex }}", bg = "{{ colors.primary_fixed.default.hex }}" }
"ui.cursor.match" = { fg = "{{ colors.on_primary_container.default.hex }}", modifiers = [
  "bold",
] }

"ui.highlight" = { bg = "{{ colors.secondary_container.default.hex }}", modifiers = [
  "bold",
] }
"ui.menu" = { fg = "{{ colors.on_surface.default.hex }}", bg = "none" }
"ui.menu.selected" = { fg = "{{ colors.primary.default.hex }}", bg = "none", modifiers = [
  "bold",
] }

# --- Diagnostics ---

"diagnostic.error" = { fg = "{{ colors.error.default.hex }}" }
"diagnostic.warning" = { fg = "{{ colors.secondary.default.hex }}" }
"diagnostic.info" = { fg = "{{ colors.tertiary.default.hex }}" }
"diagnostic.hint" = { fg = "{{ colors.tertiary_container.default.hex }}" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
blue0 = "#65aba3"

dark_red0 = "{{colors.surface.default.hex}}"
dark_red1 = "{{colors.surface_container_low.default.hex}}"
dark_red2 = "{{colors.surface_container.default.hex}}"
dark_red3 = "{{colors.surface_container_high.default.hex}}"
dark_red4 = "{{colors.surface_container_highest.default.hex}}"

dark_red5 = "{{colors.surface_bright.default.hex}}"
dark_red6 = "{{colors.on_surface_variant.default.hex}}"
dark_red7 = "{{colors.on_surface.default.hex}}"

green0 = "#8ea84d"
green1 = "#6db269"

orange0 = "#ff7550"
orange1 = "#eb842b"

# 🌸 UI ACCENT (bukan pure error)
pink0 = "{{colors.error_container.default.hex}}"
pink1 = "{{colors.error.default.hex}}"
pink2 = "{{colors.error.default.hex}}"
pink3 = "{{colors.error_container.default.hex}}"
pink4 = "{{colors.on_error.default.hex}}"

violet0 = "#ce8b9f"

white0 = "#cebabf"
