cursor_text_color     {{ colors.on_primary.dark.hex }}
url_color             {{ colors.secondary.dark.hex }}
selection_foreground  {{ colors.on_secondary.dark.hex }}
selection_background  {{ colors.secondary.dark.hex }}

mark1_foreground {{ colors.on_primary_fixed.dark.hex }}
mark1_background {{ colors.primary_fixed.dark.hex }}
mark2_foreground {{ colors.on_secondary_fixed.dark.hex }}
mark2_background {{ colors.secondary_fixed.dark.hex }}
mark3_foreground {{ colors.on_tertiary_fixed.dark.hex }}
mark3_background {{ colors.tertiary_fixed.dark.hex }}
